CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS student_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    education_level VARCHAR(255),
    learning_goal VARCHAR(255),
    CONSTRAINT fk_student_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS trainer_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    specialization VARCHAR(255),
    bio VARCHAR(1000),
    approved BOOLEAN NOT NULL,
    CONSTRAINT fk_trainer_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    created_by BIGINT NOT NULL,
    approval_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_course_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS learning_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT fk_learning_module_course FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    content VARCHAR(5000),
    image_url VARCHAR(1000),
    video_url VARCHAR(1000),
    module_id BIGINT NOT NULL,
    CONSTRAINT fk_lesson_module FOREIGN KEY (module_id) REFERENCES learning_modules (id)
);

CREATE TABLE IF NOT EXISTS question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    statement VARCHAR(1000) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    concept VARCHAR(255) NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    CONSTRAINT fk_question_module FOREIGN KEY (module_id) REFERENCES learning_modules (id)
);

CREATE TABLE IF NOT EXISTS question_options (
    question_id BIGINT NOT NULL,
    option_value VARCHAR(255),
    CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE IF NOT EXISTS enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    enrolled_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_enrollment_student_course UNIQUE (student_id, course_id),
    CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_enrollment_course FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(1000) NOT NULL,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS quiz_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    total_questions INTEGER NOT NULL,
    correct_answers INTEGER NOT NULL,
    score_percentage DOUBLE PRECISION NOT NULL,
    attempted_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_quiz_attempt_student FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_quiz_attempt_module FOREIGN KEY (module_id) REFERENCES learning_modules (id)
);

CREATE TABLE IF NOT EXISTS quiz_attempt_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_answer VARCHAR(255) NOT NULL,
    correct BOOLEAN NOT NULL,
    CONSTRAINT fk_quiz_attempt_question_attempt FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempt (id),
    CONSTRAINT fk_quiz_attempt_question_question FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE IF NOT EXISTS skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS user_skill_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    mastered BOOLEAN NOT NULL,
    CONSTRAINT uk_user_skill_level_user_skill UNIQUE (user_id, skill_id),
    CONSTRAINT fk_user_skill_level_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_skill_level_skill FOREIGN KEY (skill_id) REFERENCES skill (id)
);

CREATE TABLE IF NOT EXISTS leaderboard_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    points INTEGER NOT NULL,
    CONSTRAINT fk_leaderboard_entry_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_course_created_by ON course (created_by);
CREATE INDEX IF NOT EXISTS idx_course_approval_status ON course (approval_status);
CREATE INDEX IF NOT EXISTS idx_learning_module_course_id ON learning_modules (course_id);
CREATE INDEX IF NOT EXISTS idx_lesson_module_id ON lesson (module_id);
CREATE INDEX IF NOT EXISTS idx_question_module_id ON question (module_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_student_id ON enrollment (student_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_course_id ON enrollment (course_id);
CREATE INDEX IF NOT EXISTS idx_notification_user_id ON notification (user_id);
CREATE INDEX IF NOT EXISTS idx_notification_user_read ON notification (user_id, read);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_student_id ON quiz_attempt (student_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_module_id ON quiz_attempt (module_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_question_attempt_id ON quiz_attempt_question (quiz_attempt_id);
CREATE INDEX IF NOT EXISTS idx_user_skill_level_user_id ON user_skill_level (user_id);
CREATE INDEX IF NOT EXISTS idx_user_skill_level_skill_id ON user_skill_level (skill_id);
