CREATE TABLE IF NOT EXISTS student_doubt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT,
    module_id BIGINT,
    concept VARCHAR(255) NOT NULL,
    question VARCHAR(2000) NOT NULL,
    status VARCHAR(50) NOT NULL,
    resolution VARCHAR(3000),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by BIGINT,
    CONSTRAINT fk_student_doubt_student FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_student_doubt_course FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_student_doubt_module FOREIGN KEY (module_id) REFERENCES learning_modules (id),
    CONSTRAINT fk_student_doubt_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS course_exam (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(50) NOT NULL,
    generated_by BIGINT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    question_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_course_exam_course FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_course_exam_generated_by FOREIGN KEY (generated_by) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS course_exam_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    module_id BIGINT,
    statement VARCHAR(1200) NOT NULL,
    concept VARCHAR(255) NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    explanation VARCHAR(2000),
    CONSTRAINT fk_course_exam_question_exam FOREIGN KEY (exam_id) REFERENCES course_exam (id),
    CONSTRAINT fk_course_exam_question_module FOREIGN KEY (module_id) REFERENCES learning_modules (id)
);

CREATE TABLE IF NOT EXISTS course_exam_question_options (
    exam_question_id BIGINT NOT NULL,
    option_value VARCHAR(255),
    CONSTRAINT fk_course_exam_question_options_question
        FOREIGN KEY (exam_question_id) REFERENCES course_exam_question (id)
);

CREATE TABLE IF NOT EXISTS course_exam_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP,
    total_questions INTEGER NOT NULL,
    correct_answers INTEGER NOT NULL,
    score_percentage DOUBLE PRECISION NOT NULL,
    proctoring_score DOUBLE PRECISION NOT NULL,
    violation_count INTEGER NOT NULL,
    CONSTRAINT fk_course_exam_attempt_exam FOREIGN KEY (exam_id) REFERENCES course_exam (id),
    CONSTRAINT fk_course_exam_attempt_student FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS course_exam_attempt_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_attempt_id BIGINT NOT NULL,
    exam_question_id BIGINT NOT NULL,
    selected_answer VARCHAR(255) NOT NULL,
    correct BOOLEAN NOT NULL,
    CONSTRAINT fk_course_exam_attempt_answer_attempt
        FOREIGN KEY (exam_attempt_id) REFERENCES course_exam_attempt (id),
    CONSTRAINT fk_course_exam_attempt_answer_question
        FOREIGN KEY (exam_question_id) REFERENCES course_exam_question (id)
);

CREATE TABLE IF NOT EXISTS exam_proctor_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_attempt_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_exam_proctor_event_attempt FOREIGN KEY (exam_attempt_id) REFERENCES course_exam_attempt (id)
);

CREATE TABLE IF NOT EXISTS achievement_badge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    badge_code VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    awarded_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_achievement_badge_student_code UNIQUE (student_id, badge_code),
    CONSTRAINT fk_achievement_badge_student FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS course_certificate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    certificate_code VARCHAR(120) NOT NULL UNIQUE,
    issued_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_course_certificate_student_course UNIQUE (student_id, course_id),
    CONSTRAINT fk_course_certificate_student FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_course_certificate_course FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE INDEX IF NOT EXISTS idx_student_doubt_student_id ON student_doubt (student_id);
CREATE INDEX IF NOT EXISTS idx_student_doubt_status ON student_doubt (status);
CREATE INDEX IF NOT EXISTS idx_course_exam_course_id ON course_exam (course_id);
CREATE INDEX IF NOT EXISTS idx_course_exam_attempt_exam_id ON course_exam_attempt (exam_id);
CREATE INDEX IF NOT EXISTS idx_course_exam_attempt_student_id ON course_exam_attempt (student_id);
CREATE INDEX IF NOT EXISTS idx_exam_proctor_event_attempt_id ON exam_proctor_event (exam_attempt_id);
CREATE INDEX IF NOT EXISTS idx_achievement_badge_student_id ON achievement_badge (student_id);
CREATE INDEX IF NOT EXISTS idx_course_certificate_student_id ON course_certificate (student_id);
